### ISSUE TITLE
Site claims copy right license 

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/www.rust-bitcoin.org#1]
The site has `© 2023 rust-bitcoin` at the bottom of it but we use a copy left license.

**Comment by Harshil-Jani** [comment]
This is hardcoded into the theme repo. So, A common workaround could be that you fork the theme and update footer to take copyleft license.
For Example 
```
------------------------------------------------------------------------------
This project is licensed under the Creative Commons Zero v1.0 Universal License.
For more information, please visit: https://creativecommons.org/publicdomain/zero/1.0/

SPDX-License-Identifier: CC0-1.0
------------------------------------------------------------------------------

```

If you can just add the fork https://github.com/LordMathis/hugo-theme-nightfall into the `rust-bitcoin` organization then I can do the nits.

---

Edit :  NVM, I just updated the configurable option and added the different submodule for the theme which makes it possible. #5
