### ISSUE TITLE
fix: Dead links on repo

### ISSUE THREAD

**Issue by realeinherjar** [rust-bitcoin/www.rust-bitcoin.org#15]
From https://github.com/rust-bitcoin/www.rust-bitcoin.org/actions/runs/6454549635/job/17520321614:

FILE: cookbook/README.md

7 links checked.

FILE: cookbook/src/tx_taproot.md
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/transaction/struct.Witness.html → Status: 404
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/transaction/struct.Witness.html#impl-Default → Status: 404
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/address/struct.Address.html#method.script_pubkey → Status: 404

59 links checked.

ERROR: 3 dead links found!
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/transaction/struct.Witness.html → Status: 404
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/transaction/struct.Witness.html#impl-Default → Status: 404
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/address/struct.Address.html#method.script_pubkey → Status: 404

FILE: cookbook/src/tx_segwit-v0.md
[✖] mid-2023. → Status: 400 [Error: ENOENT: no such file or directory, access '/github/workspace/cookbook/src/mid-2023.'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/github/workspace/cookbook/src/mid-2023.'
}
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/transaction/struct.Witness.html → Status: 404
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/transaction/struct.Witness.html#impl-Default → Status: 404
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/address/struct.Address.html#method.script_pubkey → Status: 404

[52](https://github.com/rust-bitcoin/www.rust-bitcoin.org/actions/runs/6454549635/job/17520321614#step:4:53) links checked.

ERROR: 4 dead links found!
[✖] mid-2023. → Status: 400
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/transaction/struct.Witness.html → Status: 404
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/transaction/struct.Witness.html#impl-Default → Status: 404
[✖] https://docs.rs/bitcoin/latest/bitcoin/blockdata/address/struct.Address.html#method.script_pubkey → Status: 404

**Comment by realeinherjar** [comment]
> FILE: cookbook/src/tx_segwit-v0.md
> [✖] mid-2023. → Status: 400 [Error: ENOENT: no such file or directory, access '/github/workspace/cookbook/src/mid-2023.']

For this one, we can [disable the check](https://github.com/gaurav-nelson/github-action-markdown-link-check?tab=readme-ov-file#disable-check-for-some-links) with:

```md
<!-- markdown-link-check-disable -->
## Section

Disable link checking in this section. Ignore this [Bad Link](https://exampleexample.cox)
<!-- markdown-link-check-enable -->
```

**Comment by tcharding** [comment]
~How did you find all these, manually clicking on them or by running a script?~ Ah the check-links github action, I see it now.
