### ISSUE TITLE
Generated HTML does not include the logo

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/www.rust-bitcoin.org#6]
When I originally made the site I've gone and edited the HTML that is built by Hugo _after_ building it. This means when we re-build it the logo gets dropped. Thanks former Tobin, that is an hour of my life I'll never get back :)

See commit: `commit 9be7234 Add bitcoin logo` for what needs to be added.

**Comment by realeinherjar** [comment]
Is this still relevant?
<https://rust-bitcoin.org/> has a logo.
Did you mean a favicon?

**Comment by tcharding** [comment]
The issue is with the build script, I believe it is still relevant, but if #9 goes in and the `build.sh` script gets removed then this issue goes stale I believe.
