### ISSUE TITLE
Add RSS feed so folks can subscribe to the blogpost

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/www.rust-bitcoin.org#7]
Currently the blog post is just static content generated by Hugo. It would be cool if folks could subscribe to get new posts.

**Comment by apoelstra** [comment]
My personal blog is static (generated by Pelican) and it has an RSS feed. So there's no reason in principle we can't do this.

**Comment by realeinherjar** [comment]
I don't know if you guys are aware, but this is already done today.

Nightfall theme generates RSS by default (check https://github.com/LordMathis/hugo-theme-nightfall/issues/16).

If you go to <https://rust-bitcoin.org/index.xml> you'll see the feed.

Additionally, I've tested with my RSS reader. If you add <https://rust-bitcoin.org> it will find the RSS feed and render everything OK.
Here's a pic:
<img width="1185" alt="image" src="https://github.com/rust-bitcoin/www.rust-bitcoin.org/assets/136860407/c408fc5d-9de6-4cd6-bea3-50bb432059de">

We can close this

**Comment by tcharding** [comment]
Gee, you are a useful bloke to have about @realeinherjar.
